version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - mysql
            - mssql
    mssql:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "YourStrong!Passw0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        networks:
            - sail
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        networks:
            - sail
networks:
    sail:
        driver: bridge
