USE [WEMI_MISC]
GO
SET IDENTITY_INSERT [dbo].[users] OFF 

INSERT [dbo].[users] ([first_name], [middle_name], [last_name], [role], [email], [email_verified_at], [password], [remember_token], [created_at], [updated_at]) VALUES
(N'Aisha', N'Mika S.', N'Bagarino', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Aj', NULL, N'Morales', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Aleah', NULL, N'Camacho', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Allan', NULL, N'Fordan', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Althea', NULL, N'Quijano', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Andrei', NULL, N'Sacro', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Angelo', NULL, N'Marquez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Aniceta', N'V.', N'Pardo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Arlene', N'L.', N'Pedernal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ashly', N'Genes', N'Felow', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ayesha', N'Faith O.', N'Colot', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Azecca', N'M.', N'Celeste', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Beth', NULL, N'Quijano', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'BJS', NULL, N'Ingal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Brix', NULL, N'Terrenal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Cesar', NULL, N'Pareja', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Conn', N'Miguel P.', N'Pardo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Cristy', NULL, N'Unico', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Calvin', NULL, N'Terrenal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Cyja', NULL, N'Morales', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Daniel', NULL, N'Marquez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Danielle', NULL, N'Bolea', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Danilo', NULL, N'Bolea', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Daryl', NULL, N'Bolea', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'David', NULL, N'Domingo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Domingo', NULL, N'Basbas', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Domingo', NULL, N'Rareza', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Donnil', NULL, N'Bolea', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Edgar', N'E.', N'Pardo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Edwin', NULL, N'Caling', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Eleston', NULL, N'Nemer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Eliab', N'M.', N'Celeste', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Elliston', N'T.', N'Nimer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ellizer', N'T.', N'Nimer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Elmer', NULL, N'Gordula', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Emmanual', NULL, N'Nimer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Emmerson', NULL, N'Maruya', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ezekiel', NULL, N'Fordan', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Franchesca', N'C.', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Franz', NULL, N'Marquez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Fronas', NULL, N'Zapata', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Genesis', N'James C.', N'Pardo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Gerlie', NULL, N'Terrenal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Heal', N'Joshua C.', N'Pardo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jacob', NULL, N'Marquez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jane', NULL, N'Tabafunda', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jay', NULL, N'Cabrera', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jay', N'E.', N'Asis', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jaypee', NULL, N'Marquez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jeanette', NULL, N'Oliguer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jency', NULL, N'Castillo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jerick', NULL, N'Quijano', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jocelyn', NULL, N'Jowen', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'John', N'Emmanual J.', N'Morales', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jojo', NULL, N'Elomina', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Joni', NULL, N'Tolentino', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Jorean', NULL, N'Espinosa', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Josua', N'Dave', N'Olivera', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Joyce', NULL, N'Revilla', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Katherine', NULL, N'Adamos', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Keisha', N'H.', N'Pielago', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Kyla', N'Mae S.', N'Ingal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Linda', NULL, N'Domingo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'LJ', NULL, N'Olaguer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Lourdes', NULL, N'Fordan', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Luz', NULL, N'Bolea', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Mafe', N'A.', N'Ensinares', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Maica', NULL, N'Estuaria', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Makaila', N'Colleen T.', N'Malricio', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Marc', N'Laurence', N'Rodriguez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Marilyn', NULL, N'Floralde', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Marina', NULL, N'Pareja', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Marvin', NULL, N'Montana', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Mary', N'Loraine B.', N'Dy Pico', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Maylene', NULL, N'Bernal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Michael', N'V.', N'Pardo', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Michella', N'B.', N'Dy Pico', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Miguel', N'D.', N'Colot', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Mina', NULL, N'Valendrez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Nena', N'C.', N'Egtub', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Nino', N'Yanael M.', N'Hain', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Novelita', N'D.', N'Bagting', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Oliver', NULL, N'Marquez', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Rafael', NULL, N'Bernal', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Reynaldo', NULL, N'Ensinares', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Romy', NULL, N'Felow', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ronald', NULL, N'Batusis', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Sarah', N'M.', N'Abla', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Shirly', NULL, N'Casalme', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Stephanie', NULL, N'Capurihan', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Telly', NULL, N'Alcuran', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Tricia', NULL, N'Batusis', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Tristan', NULL, N'Olaguer', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Vivian', NULL, N'Gusi', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Wena', NULL, N'Caling', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Chesny', NULL, N'Ravena Dinaab', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ryan', N'Cyrus', N'Jimson', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Matthew', NULL, N'Fordan', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Eunice', NULL, N'Fordan', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Alexandra', NULL, N'Barrera', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Irma', NULL, N'Camacho', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ayezha', NULL, N'Santos', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Christian', NULL, N'Espiridion', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Ester', NULL, N'Cabrera', 0, NULL, NULL, NULL, NULL, NULL, NULL),
(N'Clark', NULL, N'Violeta', 0, NULL, NULL, NULL, NULL, NULL, NULL);
