<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 10px;
            color: #333;
        }
        header, footer {
            text-align: center;
            margin-bottom: 10px;
        }
        header h1 {
            font-size: 18px;
            margin-bottom: 5px;
        }
        header p {
            font-size: 12px;
            color: #777;
        }
        footer p {
            font-size: 10px;
            color: #777;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 12px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            color: #333;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .number-column {
            width: 5%;
            text-align: center;
        }
    </style>
</head>
<body>

<header>
    <h1>Attendance Report</h1>
    <p>Date: {{ date('Y-m-d') }}</p>
</header>

<h2>Attendance List</h2>

<table>
    <thead>
    <tr>
        <th class="number-column">#</th>
        <th>Full Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($attendances as $index => $attendance)
        <tr>
            <td class="number-column">{{ $index + 1 }}</td>
            <td>{{ $attendance->user->first_name }} {{ $attendance->user->last_name }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<footer>
    <p>Generated by Word Expansion For Mission International | Confidential</p>
</footer>

</body>
</html>
